version: 2
updates:
  - package-ecosystem: "uv"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      uv-all:
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
      uv-major:
        patterns: ["*"]
        update-types:
          - "major"
      uv-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-all:
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
      docker-major:
        patterns: ["*"]
        update-types:
          - "major"
      docker-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 7
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-all:
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
      actions-major:
        patterns: ["*"]
        update-types:
          - "major"
      actions-security:
        applies-to: security-updates
        patterns: ["*"]
        update-types:
          - "minor"
          - "patch"
