"""Update check - Tests."""

import json
import os
import tempfile
import unittest
from unittest import mock

from .. import update_check, version

MANIFEST_TEXT = (
    "# Generated by the standalone CLI release workflow. Do not edit manually.\n"
    "schema=1\n"
    "version=1.26.0\n"
    "target=macos-arm64\n"
    "archive=cloudsmith-1.26.0-macos-arm64.tar.gz\n"
    "url=https://dl.cloudsmith.io/example.tar.gz\n"
    "sha256=abc123\n"
)


class TestParseManifest(unittest.TestCase):
    def test_parses_key_value_lines(self):
        manifest = update_check.parse_manifest(MANIFEST_TEXT)
        self.assertEqual("1.26.0", manifest["version"])
        self.assertEqual("abc123", manifest["sha256"])

    def test_skips_comments_and_blank_lines(self):
        manifest = update_check.parse_manifest("# comment\n\nversion=1.0.0\n")
        self.assertEqual({"version": "1.0.0"}, manifest)


class TestFetchLatestManifest(unittest.TestCase):
    def setUp(self):
        patcher = mock.patch("cloudsmith_cli.core.session.create_requests_session")
        self.addCleanup(patcher.stop)
        self.get_mock = patcher.start().return_value.get

    def test_fetches_probe_target_manifest(self):
        self.get_mock.return_value.text = MANIFEST_TEXT
        manifest = update_check.fetch_latest_manifest()
        expected_url = update_check.MANIFEST_URL_TEMPLATE.format(
            target=update_check.VERSION_PROBE_TARGET
        )
        self.get_mock.assert_called_once_with(expected_url, timeout=5.0)
        self.get_mock.return_value.raise_for_status.assert_called_once_with()
        self.assertEqual("1.26.0", manifest["version"])

    def test_fetches_explicit_target_manifest(self):
        self.get_mock.return_value.text = MANIFEST_TEXT
        update_check.fetch_latest_manifest(target="macos-arm64", timeout=2.0)
        expected_url = update_check.MANIFEST_URL_TEMPLATE.format(target="macos-arm64")
        self.get_mock.assert_called_once_with(expected_url, timeout=2.0)

    def test_rejects_manifest_without_version(self):
        self.get_mock.return_value.text = "schema=1\n"
        with self.assertRaises(ValueError):
            update_check.fetch_latest_manifest()


class TestCachedState(unittest.TestCase):
    def setUp(self):
        self.tmp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp_dir.cleanup)
        self.cache_file = os.path.join(self.tmp_dir.name, "update_check.json")
        patcher = mock.patch.object(
            update_check, "get_cache_file_path", return_value=self.cache_file
        )
        self.addCleanup(patcher.stop)
        patcher.start()

    def test_round_trip(self):
        with mock.patch("time.time", return_value=1000.0):
            update_check.write_cached_state("1.26.0")
        state = update_check.read_cached_state()
        self.assertEqual("1.26.0", state["latest_version"])
        self.assertEqual(1000.0, state["checked_at"])

    def test_read_returns_empty_dict_when_missing(self):
        self.assertEqual({}, update_check.read_cached_state())

    def test_read_returns_empty_dict_when_corrupt(self):
        with open(self.cache_file, "w", encoding="utf-8") as cache:
            cache.write("not json")
        self.assertEqual({}, update_check.read_cached_state())

    def test_read_returns_empty_dict_when_not_an_object(self):
        with open(self.cache_file, "w", encoding="utf-8") as cache:
            json.dump(["1.26.0"], cache)
        self.assertEqual({}, update_check.read_cached_state())


class TestCacheIsFresh(unittest.TestCase):
    def test_fresh_within_interval(self):
        state = {"checked_at": 1000.0, "latest_version": "1.26.0"}
        self.assertTrue(update_check.cache_is_fresh(state, now=1000.0 + 3600))

    def test_stale_after_interval(self):
        state = {"checked_at": 1000.0, "latest_version": "1.26.0"}
        stale_now = 1000.0 + update_check.DEFAULT_INTERVAL_SECONDS + 1
        self.assertFalse(update_check.cache_is_fresh(state, now=stale_now))

    def test_stale_when_empty(self):
        self.assertFalse(update_check.cache_is_fresh({}, now=1000.0))

    def test_stale_when_checked_at_invalid(self):
        state = {"checked_at": "bad", "latest_version": "1.26.0"}
        self.assertFalse(update_check.cache_is_fresh(state, now=1000.0))


class TestUpdateCheckEnabled(unittest.TestCase):
    def setUp(self):
        self.opts = mock.Mock()
        self.opts.output = "pretty"
        env_patcher = mock.patch.dict(os.environ, {}, clear=False)
        self.addCleanup(env_patcher.stop)
        env_patcher.start()
        os.environ.pop("CLOUDSMITH_NO_UPDATE_CHECK", None)
        os.environ.pop("CI", None)
        tty_patcher = mock.patch.object(
            update_check, "stderr_is_tty", return_value=True
        )
        self.addCleanup(tty_patcher.stop)
        tty_patcher.start()

    def test_enabled_by_default(self):
        self.assertTrue(update_check.update_check_enabled(self.opts, "status"))

    def test_disabled_by_env_var(self):
        os.environ["CLOUDSMITH_NO_UPDATE_CHECK"] = "1"
        self.assertFalse(update_check.update_check_enabled(self.opts, "status"))

    def test_disabled_in_ci(self):
        os.environ["CI"] = "true"
        self.assertFalse(update_check.update_check_enabled(self.opts, "status"))

    def test_disabled_without_tty(self):
        update_check.stderr_is_tty.return_value = False
        self.assertFalse(update_check.update_check_enabled(self.opts, "status"))

    def test_disabled_for_json_output(self):
        self.opts.output = "json"
        self.assertFalse(update_check.update_check_enabled(self.opts, "status"))

    def test_disabled_for_mcp_and_upgrade(self):
        self.assertFalse(update_check.update_check_enabled(self.opts, "mcp"))
        self.assertFalse(update_check.update_check_enabled(self.opts, "upgrade"))


class TestGetAvailableUpdate(unittest.TestCase):
    def _state(self, latest):
        return {"checked_at": 1000.0, "latest_version": latest}

    def setUp(self):
        patcher = mock.patch.object(version, "get_version", return_value="1.25.0")
        self.addCleanup(patcher.stop)
        patcher.start()

    def test_returns_newer_version(self):
        with mock.patch.object(
            update_check, "read_cached_state", return_value=self._state("1.26.0")
        ):
            self.assertEqual("1.26.0", update_check.get_available_update())

    def test_returns_none_when_current(self):
        with mock.patch.object(
            update_check, "read_cached_state", return_value=self._state("1.25.0")
        ):
            self.assertIsNone(update_check.get_available_update())

    def test_returns_none_when_older(self):
        with mock.patch.object(
            update_check, "read_cached_state", return_value=self._state("1.24.0")
        ):
            self.assertIsNone(update_check.get_available_update())

    def test_returns_none_when_invalid(self):
        with mock.patch.object(
            update_check, "read_cached_state", return_value=self._state("nonsense")
        ):
            self.assertIsNone(update_check.get_available_update())

    def test_returns_none_when_cache_empty(self):
        with mock.patch.object(update_check, "read_cached_state", return_value={}):
            self.assertIsNone(update_check.get_available_update())


class TestStartBackgroundCheck(unittest.TestCase):
    def test_skips_when_cache_fresh(self):
        state = {"checked_at": 1000.0, "latest_version": "1.26.0"}
        with (
            mock.patch.object(update_check, "read_cached_state", return_value=state),
            mock.patch("time.time", return_value=1000.0 + 60),
        ):
            self.assertIsNone(update_check.start_background_check_if_stale())

    def test_fetches_and_caches_when_stale(self):
        with (
            mock.patch.object(update_check, "read_cached_state", return_value={}),
            mock.patch.object(
                update_check,
                "fetch_latest_manifest",
                return_value={"version": "1.26.0"},
            ),
            mock.patch.object(update_check, "write_cached_state") as write_mock,
        ):
            thread = update_check.start_background_check_if_stale()
            self.assertIsNotNone(thread)
            thread.join(timeout=5)
            write_mock.assert_called_with("1.26.0")

    def test_stamps_state_before_the_fetch(self):
        state = {"checked_at": 0.0, "latest_version": "1.24.0"}
        with (
            mock.patch.object(update_check, "read_cached_state", return_value=state),
            mock.patch.object(
                update_check,
                "fetch_latest_manifest",
                return_value={"version": "1.26.0"},
            ),
            mock.patch.object(update_check, "write_cached_state") as write_mock,
        ):
            thread = update_check.start_background_check_if_stale()
            thread.join(timeout=5)
            self.assertEqual(mock.call("1.24.0"), write_mock.call_args_list[0])

    def test_swallows_fetch_errors(self):
        with (
            mock.patch.object(update_check, "read_cached_state", return_value={}),
            mock.patch.object(
                update_check,
                "fetch_latest_manifest",
                side_effect=OSError("network down"),
            ),
            mock.patch.object(update_check, "write_cached_state") as write_mock,
        ):
            thread = update_check.start_background_check_if_stale()
            thread.join(timeout=5)
            write_mock.assert_called_once_with(None)

    def test_skips_when_state_unwritable(self):
        with (
            mock.patch.object(update_check, "read_cached_state", return_value={}),
            mock.patch.object(
                update_check, "write_cached_state", side_effect=OSError("denied")
            ),
        ):
            self.assertIsNone(update_check.start_background_check_if_stale())


class TestPrintUpdateNotice(unittest.TestCase):
    @mock.patch("cloudsmith_cli.core.update_check.click.secho")
    def test_prints_notice_when_update_available(self, secho_mock):
        with (
            mock.patch.object(
                update_check, "get_available_update", return_value="1.26.0"
            ),
            mock.patch.object(version, "get_version", return_value="1.25.0"),
        ):
            update_check.print_update_notice_if_available()
        output = " ".join(str(call) for call in secho_mock.call_args_list)
        self.assertIn("1.25.0", output)
        self.assertIn("1.26.0", output)
        self.assertIn("cloudsmith upgrade", output)
        for call in secho_mock.call_args_list:
            self.assertTrue(call.kwargs.get("err"))

    @mock.patch("cloudsmith_cli.core.update_check.click.secho")
    def test_silent_when_no_update(self, secho_mock):
        with mock.patch.object(update_check, "get_available_update", return_value=None):
            update_check.print_update_notice_if_available()
        secho_mock.assert_not_called()


class TestStderrIsTty(unittest.TestCase):
    def test_false_when_stderr_is_missing(self):
        with mock.patch.object(update_check.sys, "stderr", None):
            self.assertFalse(update_check.stderr_is_tty())


class TestArm(unittest.TestCase):
    def setUp(self):
        self.opts = mock.Mock()
        self.opts.output = "pretty"
        env_patcher = mock.patch.dict(os.environ, {}, clear=False)
        self.addCleanup(env_patcher.stop)
        env_patcher.start()
        os.environ.pop("CLOUDSMITH_NO_UPDATE_CHECK", None)
        os.environ.pop("CI", None)
        tty_patcher = mock.patch.object(
            update_check, "stderr_is_tty", return_value=True
        )
        self.addCleanup(tty_patcher.stop)
        tty_patcher.start()
        start_patcher = mock.patch.object(
            update_check, "start_background_check_if_stale", return_value=None
        )
        self.addCleanup(start_patcher.stop)
        self.start_mock = start_patcher.start()

    def _context(self, invoked="status", inverse=None):
        ctx = mock.Mock()
        ctx.invoked_subcommand = invoked
        ctx.command.inverse = inverse if inverse is not None else {}
        return ctx

    def test_arms_for_regular_command(self):
        ctx = self._context()
        update_check.arm(ctx, self.opts)
        self.start_mock.assert_called_once_with()
        ctx.call_on_close.assert_called_once()

    def test_suppresses_alias_of_suppressed_command(self):
        ctx = self._context(invoked="update", inverse={"update": "upgrade"})
        update_check.arm(ctx, self.opts)
        self.start_mock.assert_not_called()

    def test_close_callback_respects_late_json_output(self):
        ctx = self._context()
        update_check.arm(ctx, self.opts)
        close_callback = ctx.call_on_close.call_args[0][0]
        self.opts.output = "json"
        with mock.patch.object(
            update_check, "print_update_notice_if_available"
        ) as notice_mock:
            close_callback()
        notice_mock.assert_not_called()

    def test_close_callback_joins_background_thread(self):
        thread = mock.Mock()
        self.start_mock.return_value = thread
        ctx = self._context()
        update_check.arm(ctx, self.opts)
        close_callback = ctx.call_on_close.call_args[0][0]
        with mock.patch.object(update_check, "print_update_notice_if_available"):
            close_callback()
        thread.join.assert_called_once_with(
            update_check.BACKGROUND_JOIN_TIMEOUT_SECONDS
        )
