name: Type check
on:
  pull_request:
    branches:
      - "**"
jobs:
  ty:
    - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        enable-cache: true
    - run: uv sync --locked --group dev
    - run: uv run ty check --warn all --output-format=github
