"""Tests that every shipped entrypoint reports API failures as an exit code.

``AliasGroup.main`` runs click with ``standalone_mode=False`` so it can render
click's own errors as JSON, which means click *returns* the code passed to
``ctx.exit()`` instead of raising ``SystemExit``. Every entrypoint therefore has
to wrap ``main()`` in ``sys.exit()``; one that calls it bare exits 0 on a failed
command, and a caller (CI, a script) sees a push or an auth failure as success.
"""

import pathlib
import runpy
import sys
from unittest.mock import patch

import pytest

from cloudsmith_cli.cli.commands.main import main
from cloudsmith_cli.core.api.exceptions import ApiException

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]

# The entrypoints that are not importable as modules: the console script is
# generated by the installer from [project.scripts], and the PyInstaller entry
# only runs under __main__ in the frozen bundle.
UNIMPORTABLE_ENTRYPOINTS = [
    REPO_ROOT / "packaging" / "pyinstaller" / "entry.py",
]


def unauthorised_args(config_dir):
    """Return args for a whoami that will raise a 401, isolated from real config."""
    return [
        "whoami",
        "--config-file",
        str(config_dir),
        "--credentials-file",
        str(config_dir),
        "--api-host",
        "https://api.example.invalid",
        "--api-key",
        "fake-api-key",
    ]


def unauthorised_api():
    """Patch the whoami API call to raise a 401."""
    return patch(
        "cloudsmith_cli.cli.commands.whoami.get_user_brief",
        side_effect=ApiException(status=401, detail="Invalid API key"),
    )


def test_main_returns_the_status_as_an_exit_code(tmp_path):
    """The value entrypoints must pass to sys.exit() - not a raised SystemExit."""
    with unauthorised_api():
        assert main(unauthorised_args(tmp_path), standalone_mode=True) == 401


def test_python_m_exits_non_zero(tmp_path, monkeypatch):
    monkeypatch.setattr(sys, "argv", ["cloudsmith", *unauthorised_args(tmp_path)])

    with unauthorised_api(), pytest.raises(SystemExit) as exc_info:
        runpy.run_module("cloudsmith_cli", run_name="__main__")

    assert exc_info.value.code == 401


@pytest.mark.parametrize("path", UNIMPORTABLE_ENTRYPOINTS, ids=lambda p: p.name)
def test_unimportable_entrypoint_wraps_main_in_sys_exit(path):
    if not path.is_file():
        pytest.skip(f"{path} is not present (not shipped in the distribution)")

    assert "sys.exit(main())" in path.read_text()
